# Generated by Django 3.1.2 on 2021-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Detail',
            fields=[
                ('Supplier_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Supplier_name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Contact', models.CharField(default=None, max_length=10)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Nature_of_business', models.CharField(max_length=30)),
                ('GST_no', models.CharField(max_length=30)),
                ('Distributor', models.CharField(max_length=20)),
                ('List_of_item', models.CharField(max_length=50)),
                ('Details', models.TextField(default=None)),
                ('Details_file', models.FileField(default=None, upload_to='')),
                ('Facilities', models.TextField(default=None)),
                ('Facilities_file', models.FileField(default=None, upload_to='')),
                ('Information', models.TextField()),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
            ],
        ),
    ]
