# Generated by Django 3.1.7 on 2021-04-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Detail',
            fields=[
                ('Supplier_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Supplier_name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Contact', models.CharField(default=None, max_length=10)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Nature_of_business', models.CharField(max_length=30)),
                ('GST_no', models.CharField(max_length=30)),
                ('Distributor', models.CharField(max_length=20)),
                ('List_of_item', models.CharField(max_length=50)),
                ('Details', models.TextField(default=None)),
                ('Details_file', models.FileField(default=None, upload_to='')),
                ('Facilities', models.TextField(default=None)),
                ('Facilities_file', models.FileField(default=None, upload_to='')),
                ('Information', models.TextField()),
                ('Datime', models.DateTimeField()),
                ('Prepared_by', models.BooleanField(default=False)),
                ('Approved_by', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOQ', models.IntegerField()),
                ('Qty_WD', models.IntegerField()),
                ('Qty_W7D', models.IntegerField()),
                ('Qty_PFP', models.IntegerField()),
                ('Qty_ILS', models.IntegerField()),
                ('DR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TQR', models.IntegerField()),
                ('Ta_AWOD', models.IntegerField()),
                ('Ta_AWD', models.IntegerField()),
                ('IRD', models.IntegerField()),
                ('QR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Prepared_by', models.BooleanField(default=False)),
                ('Approved_by', models.BooleanField(default=False)),
                ('Datime', models.DateTimeField()),
                ('Supplier_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.TextField()),
                ('Period', models.CharField(max_length=100)),
                ('Consistent_quality', models.BigIntegerField()),
                ('Technical_capability', models.BigIntegerField()),
                ('Experience', models.BigIntegerField()),
                ('Credit_terms', models.BigIntegerField()),
                ('Capability_to_meet', models.BigIntegerField()),
                ('Quality', models.BigIntegerField()),
                ('Total', models.BigIntegerField()),
                ('Meeting_schedule', models.BigIntegerField()),
                ('Conclusion', models.CharField(max_length=50)),
                ('Assessed_by', models.BooleanField(default=False)),
                ('Approved_by', models.BooleanField(default=False)),
                ('Datime', models.DateTimeField()),
                ('Supplier_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term_1', models.IntegerField()),
                ('Term_2', models.IntegerField()),
                ('Term_3', models.IntegerField()),
                ('Term_4', models.IntegerField()),
                ('Term_5', models.IntegerField()),
                ('Term_6', models.IntegerField()),
                ('Term_7', models.IntegerField()),
                ('Term_8', models.IntegerField()),
                ('Term_9', models.IntegerField()),
                ('Term_10', models.IntegerField()),
                ('Supplier_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier_detail')),
            ],
        ),
    ]
