# Generated by Django 3.1.2 on 2021-01-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Detail',
            fields=[
                ('Supplier_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Supplier_name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Contact', models.CharField(default='None', max_length=10)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Nature_of_business', models.CharField(max_length=30)),
                ('Sales_tax', models.CharField(max_length=30)),
                ('Distributor', models.CharField(max_length=20)),
                ('List_of_item', models.CharField(max_length=50)),
                ('Details_of_presnt_reputed_customers', models.CharField(max_length=50)),
                ('Facilities_instruments_available', models.CharField(max_length=30)),
                ('Equipments', models.CharField(max_length=50)),
                ('Instruments', models.CharField(max_length=50)),
                ('Any_other_information', models.TextField()),
                ('Date', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=10)),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
                ('Supplier_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier_detail')),
            ],
        ),
    ]
