# Generated by Django 3.1.2 on 2021-01-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_detail',
            name='Approved_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier_detail',
            name='Prepared_by',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Supplier_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_code', models.CharField(max_length=50)),
                ('Items', models.TextField()),
                ('Period', models.CharField(max_length=100)),
                ('Consistent_quality', models.BigIntegerField()),
                ('Technical_capability', models.BigIntegerField()),
                ('Experience', models.BigIntegerField()),
                ('Credit_terms', models.BigIntegerField()),
                ('Capability_to_meet', models.BigIntegerField()),
                ('Quality', models.BigIntegerField()),
                ('Total', models.BigIntegerField()),
                ('Meeting_schedule', models.BigIntegerField()),
                ('Conclusion', models.CharField(max_length=50)),
                ('Assessed_by', models.BooleanField(default=False)),
                ('Approved_by', models.BooleanField(default=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Supplier_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier_detail')),
            ],
        ),
    ]
