# Generated by Django 3.1.2 on 2021-01-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20210111_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOQ', models.IntegerField()),
                ('Qty_WD', models.IntegerField()),
                ('Qty_W7D', models.IntegerField()),
                ('Qty_PFP', models.IntegerField()),
                ('Qty_ILS', models.IntegerField()),
                ('DR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TQR', models.IntegerField()),
                ('Ta_AWOD', models.IntegerField()),
                ('Ta_AWD', models.IntegerField()),
                ('IRD', models.IntegerField()),
                ('QR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Prepared_by', models.BooleanField(default=False)),
                ('Approved_by', models.BooleanField(default=False)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
