# Generated by Django 3.1.2 on 2021-01-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('Customer_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Nick_name', models.CharField(max_length=30)),
                ('Contact', models.CharField(default=None, max_length=50)),
                ('Address', models.TextField()),
                ('GST_no', models.CharField(max_length=30)),
                ('CIN_no', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(default='None', max_length=254)),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('RFQ_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
                ('Customer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customer_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('Product_id', models.CharField(default='None', max_length=30, primary_key=True, serialize=False)),
                ('Ventor_code', models.CharField(max_length=15, null=True)),
                ('Part_code', models.CharField(max_length=15)),
                ('Part_name', models.CharField(max_length=15)),
                ('Casting_type', models.CharField(max_length=15)),
                ('Pattern_scope', models.CharField(max_length=20)),
                ('Transport', models.CharField(max_length=20, null=True)),
                ('Painting_method', models.CharField(max_length=20, null=True)),
                ('Packing_type', models.CharField(max_length=24, null=True)),
                ('Machinary_type', models.CharField(max_length=24, null=True)),
                ('Payment_terms', models.CharField(max_length=24, null=True)),
                ('Export_required', models.CharField(max_length=5)),
                ('Payments_terms_days', models.CharField(default=None, max_length=10, null=True)),
                ('Quantity', models.CharField(max_length=10)),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
                ('Is_feasiable', models.BooleanField(default=True)),
                ('RFQ_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketing.order_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=10)),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
                ('Customer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customer_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Feasibility_Detail',
            fields=[
                ('Feasibility_id', models.CharField(default='None', max_length=30, primary_key=True, serialize=False)),
                ('Drawing_readability', models.CharField(max_length=10)),
                ('Dimensional_tolerance', models.CharField(max_length=20)),
                ('Cast_material', models.CharField(max_length=20)),
                ('Hardness_required', models.CharField(max_length=20)),
                ('Resource_requirement', models.CharField(max_length=20)),
                ('Whether_all_dimensions_given', models.CharField(max_length=10)),
                ('Type_of_mould', models.CharField(max_length=20)),
                ('No_of_cavity', models.IntegerField()),
                ('Core_type', models.CharField(max_length=20)),
                ('Approx_core_weight', models.IntegerField(null=True)),
                ('Core_box_detail', models.CharField(max_length=20, null=True)),
                ('Reinforcement_in_core', models.CharField(max_length=20, null=True)),
                ('Pattern_overall_size', models.CharField(max_length=30)),
                ('Minimum_wall_thickness', models.CharField(max_length=30)),
                ('Casting_weight', models.IntegerField()),
                ('Casting_weight_per_box', models.IntegerField()),
                ('Approx_pouring_weight', models.CharField(max_length=30)),
                ('Yield', models.IntegerField()),
                ('Frame_requirement', models.CharField(max_length=30)),
                ('Chill_requirement', models.CharField(max_length=10)),
                ('Pattern_material', models.CharField(max_length=30)),
                ('Filter_requirement', models.CharField(max_length=10)),
                ('Fettling_requirement', models.CharField(max_length=30)),
                ('Pattern_core_box_cost', models.CharField(max_length=30)),
                ('Casting_surface_coating', models.CharField(max_length=30)),
                ('Match_plate_cost', models.CharField(max_length=30)),
                ('Surface_treatment_cost', models.CharField(max_length=30)),
                ('Development_cost', models.CharField(max_length=30)),
                ('PPAP', models.CharField(max_length=30)),
                ('Pattern_development_time', models.TextField()),
                ('Bulk_lot_lead_time', models.CharField(max_length=20)),
                ('Rejection_level_estimation', models.CharField(max_length=30)),
                ('Head_treatment_requirement', models.CharField(max_length=10)),
                ('Supplier_identification', models.CharField(max_length=30)),
                ('Heat_no_detail', models.CharField(max_length=30)),
                ('Conclusion', models.CharField(max_length=15)),
                ('Not_feasible_reason', models.TextField(null=True)),
                ('Customer_special_requirement', models.TextField(null=True)),
                ('BFC_constraints', models.TextField(null=True)),
                ('Comments', models.TextField(null=True)),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
                ('Product_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketing.product_detail')),
            ],
        ),
    ]
