# Generated by Django 3.1.2 on 2020-12-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ventor_code', models.CharField(max_length=15)),
                ('Part_code', models.CharField(max_length=15)),
                ('Part_name', models.CharField(max_length=15)),
                ('Casting_type', models.CharField(max_length=15)),
                ('Pattern_scope', models.CharField(max_length=20)),
                ('Transport', models.CharField(max_length=20)),
                ('Painting_method', models.CharField(max_length=20)),
                ('Packing_type', models.CharField(max_length=24)),
                ('Machinary_type', models.CharField(max_length=24)),
                ('Payment_terms', models.CharField(max_length=24)),
                ('Export_required', models.CharField(max_length=5)),
                ('Quantity', models.CharField(max_length=5)),
                ('Customer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customer_detail')),
            ],
        ),
    ]
