# Generated by Django 3.1.7 on 2021-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_detail',
            name='Email_id',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
