# Generated by Django 3.1.2 on 2020-12-22 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_order_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='Customer_detail',
            new_name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='Contact_1',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='Contact_2',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='Contact_3',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='Contact_4',
        ),
        migrations.RemoveField(
            model_name='customer_detail',
            name='Email_id',
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='Date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='Time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='Date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='Payments_terms_days',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='Time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='Customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Machinary_type',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Packing_type',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Painting_method',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Payment_terms',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Quantity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Transport',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='Ventor_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Individual_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=10)),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customer_detail')),
            ],
        ),
    ]
