# Generated by Django 3.1.2 on 2020-12-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20201222_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual_detail',
            old_name='Customer_id',
            new_name='Customer_detail',
        ),
        migrations.RenameField(
            model_name='order_detail',
            old_name='Customer_id',
            new_name='Customer_detail',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Casting_type',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Export_required',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Machinary_type',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Packing_type',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Painting_method',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Part_code',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Part_name',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Pattern_scope',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Payment_terms',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Payments_terms_days',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Transport',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='Ventor_code',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='RFQ_id',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ventor_code', models.CharField(max_length=15, null=True)),
                ('Part_code', models.CharField(max_length=15)),
                ('Part_name', models.CharField(max_length=15)),
                ('Casting_type', models.CharField(max_length=15)),
                ('Pattern_scope', models.CharField(max_length=20)),
                ('Transport', models.CharField(max_length=20, null=True)),
                ('Painting_method', models.CharField(max_length=20, null=True)),
                ('Packing_type', models.CharField(max_length=24, null=True)),
                ('Machinary_type', models.CharField(max_length=24, null=True)),
                ('Payment_terms', models.CharField(max_length=24, null=True)),
                ('Export_required', models.CharField(max_length=5)),
                ('Payments_terms_days', models.CharField(default=None, max_length=10, null=True)),
                ('Quantity', models.CharField(max_length=10)),
                ('Date', models.DateField(default=None, null=True)),
                ('Time', models.TimeField(default=None, null=True)),
                ('RFQ_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.order_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Feasibility_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drawing_readbility', models.CharField(max_length=10)),
                ('Dimensional_tolerance', models.CharField(max_length=20)),
                ('Cast_material', models.CharField(max_length=20)),
                ('Hardness_required', models.CharField(max_length=20)),
                ('Resource_requirement', models.CharField(max_length=20)),
                ('Whether_all_dimensions_given', models.CharField(max_length=10)),
                ('Type_of_mould', models.CharField(max_length=20)),
                ('No_of_cavity', models.IntegerField()),
                ('Core_type', models.CharField(max_length=20)),
                ('Approx_core_weight', models.IntegerField(null=True)),
                ('Core_box_detail', models.CharField(max_length=20, null=True)),
                ('Reinforcement_in_core', models.CharField(max_length=20, null=True)),
                ('Pattern_overall_size', models.CharField(max_length=30)),
                ('Minimum_wall_thickness', models.CharField(max_length=30)),
                ('Casting_weight', models.IntegerField()),
                ('Casting_weight_per_box', models.IntegerField()),
                ('Approx_pouring_weight', models.CharField(max_length=30)),
                ('Yield', models.IntegerField()),
                ('Frame_requirement', models.CharField(max_length=30)),
                ('Chill_requirement', models.CharField(max_length=10)),
                ('Pattern_material', models.CharField(max_length=30)),
                ('Filter_requirement', models.CharField(max_length=10)),
                ('Fettling_requirement', models.CharField(max_length=30)),
                ('Pattern_core_box_cost', models.CharField(max_length=30)),
                ('Casting_surface_coating', models.CharField(max_length=30)),
                ('Match_plate_cost', models.CharField(max_length=30)),
                ('Surface_treatment_cost', models.CharField(max_length=30)),
                ('Development_cost', models.CharField(max_length=30)),
                ('PPAP', models.CharField(max_length=30)),
                ('Pattern_development_time', models.CharField(max_length=10)),
                ('Bulk_lot_lead_time', models.CharField(max_length=20)),
                ('Rejection_level_estimation', models.CharField(max_length=30)),
                ('Head_treatment_requirement', models.CharField(max_length=10)),
                ('Supplier_identification', models.CharField(max_length=30)),
                ('Heat_no_detail', models.CharField(max_length=30)),
                ('Conclusion', models.CharField(max_length=15)),
                ('Not_feasible_reason', models.TextField(null=True)),
                ('Customer_special_requirement', models.TextField(null=True)),
                ('BFC_constraints', models.TextField(null=True)),
                ('Comments', models.TextField(null=True)),
                ('Product_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.product_detail')),
            ],
        ),
    ]
