# Generated by Django 3.1.2 on 2020-12-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20201228_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibility_detail',
            name='Date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='feasibility_detail',
            name='Time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
