# Generated by Django 3.1.2 on 2020-12-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20201228_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibility_detail',
            name='Product_detail',
        ),
        migrations.RemoveField(
            model_name='feasibility_detail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='RFQ_detail',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='feasibility_detail',
            name='Feasibility_id',
            field=models.CharField(default='None', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Is_feasiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Product_id',
            field=models.CharField(default='None', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feasibility_detail',
            name='Pattern_development_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='RFQ_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
