# Generated by Django 3.1.2 on 2020-12-29 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20201229_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feasibility_detail',
            old_name='Drawing_readbility',
            new_name='Drawing_readability',
        ),
        migrations.AddField(
            model_name='feasibility_detail',
            name='Product_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketing.product_detail'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='RFQ_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketing.order_detail'),
        ),
    ]
