# Generated by Django 3.1.4 on 2021-01-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20201229_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='Contact',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='Email_id',
            field=models.EmailField(default='None', max_length=254),
        ),
    ]
