# Generated by Django 3.1.2 on 2020-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20201229_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='Contact',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='Email_id',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
